### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by mscaldas2012** [glawson6/demo-mule-spring-boot#1]
Hi,
I was trying to use this setup for my project. I cloned your repo as is and when running mvn package, I get some missing dependencies...
 
Can you make sure that all dependencies are available on public repos you have on your pom?

thanks,
Marcelo.

Here's the error:

[ERROR] Failed to execute goal on project demo-mule-spring-boot: Could not resol
ve dependencies for project net.taptech:demo-mule-spring-boot:jar:0.0.1-SNAPSHOT
: The following artifacts could not be resolved: net.java.dev.stax-utils:stax-ut
ils:jar:20080702, javax.xml.xquery:xqj-api:jar:1.0, com.yourkit:yjp-controller-a
pi-redist:jar:9.0.8, org.mule:mule-core:jar:3.9.0, org.mule.transports:mule-tran
sport-http:jar:3.9.0: Failure to find net.java.dev.stax-utils:stax-utils:jar:200
80702 in http://eip.sandbox.aimsplatform.net:8381/repository/maven-group/ was ca
ched in the local repository, resolution will not be reattempted until the updat
e interval of nexus has elapsed or updates are forced -> [Help 1]

**Comment by glawson6** [comment]
This does not appear to be a public repositoty " http://eip.sandbox.aimsplatform.net:8381/repository/maven-group/" You may need to disable your settings.xml or tell the administrator for the maven repo to allow access to public repos

**Comment by mscaldas2012** [comment]
oh Doh! forgot i had that settings.xml in place - thanks!

It's working now but only for a single file. trying to add a comma delimited list of files as in:
mules.config.files=global.xml,allExceptions.xml,transport.xml

the app crashes as soon as it tries to read the files.. last output I see is this:

2018-03-28 12:34:55.124  INFO 16820 --- [           main] n.t.a.MuleContextStart
upConfiguration    : Loading Mule config files global.xml,allExceptions.xml

then it dies...
Any comments?

**Comment by glawson6** [comment]
Increase logging. I don't know what you have in those xml files.
